# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-03-27 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0003_item_list"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ("id",)},
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together=set([("list", "text")]),
        ),
    ]
