name: test

on:
  push:
    tags:
      - "*"
    branches:
      - main
      - chapter24

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18.x]
        python-version: ["3.6"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.ci.txt ]; then pip install -r requirements.ci.txt; fi
          npm ci
      - name: Lint with flake8
        run: |
          flake8 **/*.py
      - name: Test with pytest
        run: |
          xvfb-run --auto-servernum pytest --disable-pytest-warnings --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml
        env:
          DJANGO_SETTINGS_MODULE: superlists.settings
      - name: Test with phantomjs
        run: |
          npm run test
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        if: ${{ always() }}
      - name: Upload pytest screendumps
        uses: actions/upload-artifact@v3
        with:
          name: pytest-screendumps-${{ matrix.python-version }}
          path: functional_tests/screendumps/
        if: ${{ always() }}
